### ISSUE TITLE
AttributeError: 'MjViewer' object has no attribute 'exit'

### ISSUE THREAD

**Issue by ronichester** [abr/neurorobotics-2020#16]
Dear Pawel/Travis,
I am really excited about this paper and I am trying to reproduce your rover experiment on my Notebook's CPU.
I have reasonable familiarity with nengo, nengo-gui and nengo_dl; I am currently exploring Mujoco thanks to your work.

I installed everything according to the README and as soon as I run 'rover.py' i get the following error message:
`AttributeError: 'MjViewer' object has no attribute 'exit'`
and another exception ocurred:
`IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed`

The full terminal output message is:
```
Creating window glfw
Creating window glfw
MuJoCo session created
Build finished in 0:00:00                                                      
Optimization finished in 0:00:00                                               
Construction finished in 0:00:00                                               
D:\Programming\Anaconda3\lib\site-packages\nengo\node.py:62: UserWarning: 'Node.size_out' is being overwritten with 'Node.size_in' since 'Node.output=None'
  warnings.warn(
Traceback (most recent call last):

  File "C:\Users\Schechter\AppData\Local\Temp\ipykernel_12716\1004026268.py", line 35, in <module>
    sim.run(sim_runtime)

  File "D:\Programming\Anaconda3\lib\site-packages\nengo\simulator.py", line 386, in run
    self.run_steps(steps, progress_bar=progress_bar)

  File "D:\Programming\Anaconda3\lib\site-packages\nengo\simulator.py", line 410, in run_steps
    self.step()

  File "D:\Programming\Anaconda3\lib\site-packages\nengo\simulator.py", line 421, in step
    step_fn()

  File "D:\Programming\Anaconda3\lib\site-packages\nengo\builder\processes.py", line 135, in step_simprocess
    output[...] = step_f(t.item(), np.copy(input))

  File "D:\Programming\repos\nengo-interfaces\nengo_interfaces\mujoco.py", line 210, in step
    self.exit = self.viewer.exit

AttributeError: 'MjViewer' object has no attribute 'exit'


During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File 

"C:\Users\Schechter\AppData\Local\Temp\ipykernel_12716\1004026268.py", line 64, in <module>
    direct[:, 0], "r--", alpha=0.5, lw=3, label="Ideal steering torque"

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed
```

Hope you can shed any light, maybe I am missing some update in the code.
Thanks!

**Comment by ronichester** [comment]
The message above happened with the flag:
`collect_ground_truth = True  # for plotting comparison`

From the search I did, i found there is a problem with the variable "direct" on line 346:
```
if collect_ground_truth:
            direct = np.array(net.ideal_motor_track)
            axs1[0].plot(
                direct[:, 0], "r--", alpha=0.5, lw=3, label="Ideal steering torque"
            )
```
By printing it's shape I could verify that `direct`  has shape `(0, )`  and that is why it's  producing this `IndexError`. 

Alternatively, when I put the flag `collect_ground_truth = False` I still get an error message, as follows:
```
Creating window glfw
Creating window glfw
MuJoCo session created
Build finished in 0:00:00                                                      
Optimization finished in 0:00:00                                               
Construction finished in 0:00:00                                               
D:\Programming\Anaconda3\lib\site-packages\nengo\node.py:62: UserWarning: 'Node.size_out' is being overwritten with 'Node.size_in' since 'Node.output=None'
  warnings.warn(

￼

￼
Traceback (most recent call last):

  File "D:\Programming\repos\neurorobotics-2020\rover_demo\rover.py", line 317, in <module>
    sim.run(sim_runtime)

  File "D:\Programming\Anaconda3\lib\site-packages\nengo\simulator.py", line 386, in run
    self.run_steps(steps, progress_bar=progress_bar)

  File "D:\Programming\Anaconda3\lib\site-packages\nengo\simulator.py", line 410, in run_steps
    self.step()

  File "D:\Programming\Anaconda3\lib\site-packages\nengo\simulator.py", line 421, in step
    step_fn()

  File "D:\Programming\Anaconda3\lib\site-packages\nengo\builder\processes.py", line 135, in step_simprocess
    output[...] = step_f(t.item(), np.copy(input))

  File "D:\Programming\repos\nengo-interfaces\nengo_interfaces\mujoco.py", line 210, in step
    self.exit = self.viewer.exit

AttributeError: 'MjViewer' object has no attribute 'exit'
```

**Comment by studywolf** [comment]
Hello! Glad to hear you're interested! The first error is because we're actually using a custom fork of the `mujoco-py` code, which adds an `exit` parameter. You can find that code here: https://github.com/studywolf/mujoco-py (if the `main` branch still gives an error, try the `mausspaun` branch). We've actually upgraded to use the pip installable mujoco codebase, but this code base uses the older `mujoco-py`. 

If you fix that and are able to collect, but the second error still pops up, please let me know and we can debug further!

**Comment by ronichester** [comment]
Ok, I will try your custom fork and let you know if it worked.

By the way, that was a question I had, did you upgrade the code to use the official 'mujoco' library? -> `pip install mujoco`
If so, where can I find it?
I read that mujoco-py it's considered today an old third-party implementation and is now unsupported...
I tried myself to do the required changes for the transition from` mujoco-py` to `mujoco` reading the official documentation but it was too overwhelming for my level of knowledge :(

**Comment by studywolf** [comment]
Yup, the `abr_control` branch `upgrade_mujoco` works with the latest Mujoco, but i haven't upgraded the code in this repo to work with it yet. It shouldn't be too bad, I can add it to my todo list, but it'd probably be next week to get to it. If you'd like to give it a shot, though, i can support your effort! you'll need to `pip install mujoco-python-viewer` to use the `upgrade_mujoco` branch of `abr_control`

**Comment by ronichester** [comment]
> Hello! Glad to hear you're interested! The first error is because we're actually using a custom fork of the `mujoco-py` code, which adds an `exit` parameter. You can find that code here: https://github.com/studywolf/mujoco-py (if the `main` branch still gives an error, try the `mausspaun` branch). We've actually upgraded to use the pip installable mujoco codebase, but this code base uses the older `mujoco-py`.
> 
> If you fix that and are able to collect, but the second error still pops up, please let me know and we can debug further!

Thank you for the quick reply, 
I was able to clone the `mausspaun` branch and now using this custom `mujoco-py` it worked nicely! 
By the way I am using Windows 10 and although unsupported it worked fine for me.
Great work, I appreciate it !!

A quick feedback if it could help improve this repository:
I probably didn't do it the easiest way since I am not an expert, but it would have been easier with more detailed installation instructions. I felt those were not up to date, specially with this branch cloning and custom library installation.
For windows users, these were my steps:
- Download the binaries for mujoco 2.1.0 
    - (link https://github.com/deepmind/mujoco/releases/download/2.1.0/mujoco210-windows-x86_64.zip)
- Extract the downloaded mujoco210 directory into C:\Users\your_user\.mujoco\mujoco210
- Add the bin folder to your user PATH:
    - Search box > Edit the System Environment Variables >Environment Variables
    - Edit 'Path' variable on User variables
    - New -> C:\Users\your_user\.mujoco\mujoco210\bin
- Install mujoco-py library, a compatible version (this is NOT the custom library)
    - `pip install mujoco-py==2.1.2.14`
- Clone the repository, the last updated branch
    - `git clone -b mausspaun https://github.com/studywolf/mujoco-py.git`
- Find the folder `mujoco_py` and copy it to your python distribution packages folder, overwriting all the standard files with the custom files from the repository
    - For Windows 10 users with Anaconda the standard folder is usually `C:\Anaconda3\Lib\site-packages\mujoco_py\`
- Test your installation by running python on a terminal and importing the custom `mujoco_py` library.
    -` >>> import mujoco_py`
- Since the original files were manually overwritten, the library will compile again (only the first time you import it), and if no errors were reported, the installation is complete.

**Comment by studywolf** [comment]
excellent! thank you for the write up, i'll add that to the README instructions. glad it's working for you now!
